services:
  - type: web
    name: sela-posteingang
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: TG_TOKEN
        sync: false
      - key: TG_CHAT_ID
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENDER_NAME
        sync: false
      - key: API_KEY
        sync: false
